[package]
name = "iml-agent"
version = "0.1.0-alpha.1"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
description = "Core library for Integrated Manager for Lustre Agent"
license = "MIT"
repository = "https://github.com/whamcloud/iml-agent/tree/master/iml-agent"

[dependencies]
chrono = "0.4"
clap = "2.32"
dns-lookup = "1"
env_logger = "0.6.0"
exitcode = "1.1"
futures = "0.1.25"
lazy_static = "1.3.0"
log = "0.4.6"
prettytable-rs = "0.8"
reqwest = { version = "0.9", features = ["default-tls", "tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
erased-serde = "0.3.9"
structopt = "0.2.14"
tokio = "0.1.15"
tokio-process = "0.2.3"
url = "1.7.2"



[dev-dependencies]
mockito = "0.16.0"
pretty_assertions = "0.6.1"

[[bin]]
name = "iml-agent-daemon"
path = "src/main.rs"

[[bin]]
name = "iml-agent"
path = "src/cli.rs"
